//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cakcuulatorNew.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesRu() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cakcuulatorNew.Properties.ResourcesRu", typeof(ResourcesRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сложение.
        /// </summary>
        internal static string s_addition {
            get {
                return ResourceManager.GetString("s_addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ.
        /// </summary>
        internal static string s_answer {
            get {
                return ResourceManager.GetString("s_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деление.
        /// </summary>
        internal static string s_dividing {
            get {
                return ResourceManager.GetString("s_dividing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите a.
        /// </summary>
        internal static string s_firstNum {
            get {
                return ResourceManager.GetString("s_firstNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История.
        /// </summary>
        internal static string s_history {
            get {
                return ResourceManager.GetString("s_history", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Ищет локализованную строку, похожую на Загрузка истории.
=======
        ///   Ищет локализованную строку, похожую на Загрузка.
>>>>>>> calculator
        /// </summary>
        internal static string s_load {
            get {
                return ResourceManager.GetString("s_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eng.
        /// </summary>
        internal static string s_localization {
            get {
                return ResourceManager.GetString("s_localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Умножение.
        /// </summary>
        internal static string s_multiplying {
            get {
                return ResourceManager.GetString("s_multiplying", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Ищет локализованную строку, похожую на Сохранение истории.
=======
        ///   Ищет локализованную строку, похожую на Сохранение .
>>>>>>> calculator
        /// </summary>
        internal static string s_save {
            get {
                return ResourceManager.GetString("s_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите b.
        /// </summary>
        internal static string s_secondNum {
            get {
                return ResourceManager.GetString("s_secondNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вычитание.
        /// </summary>
        internal static string s_subtracting {
            get {
                return ResourceManager.GetString("s_subtracting", resourceCulture);
            }
        }
    }
}
